### ISSUE TITLE
klasa powinna być w pakiecie zgodnym z jej odpowiedzialnością

### ISSUE THREAD

**Issue by johnny333** [Salonce/WeatherAndClothes#6]
https://github.com/Salonce/WeatherAndClothes/blob/404f2f20526db4d1a439aee1e5a253b8be1bc9e0/src/main/java/springTwo/example/springProject/Weather/WeatherService.java#LL1C1-L1C1

**Comment by johnny333** [comment]
to tyczy się wszystkich klas w tym projekcie 
pakietować można na różny sposób, ale najprostrzy to 
dtos, controllers,  services, configurations, entities, repositories, generalnie polecam poczytać o np. port and adapters

**Comment by johnny333** [comment]
stosując pakiet np. dto nie musissz ubogacać nazwy klasy o dto

**Comment by johnny333** [comment]
zobacz ten projekt, typowa przelotka jak u Ciebie, tylko z trochę inną usługą 
https://github.com/johnny333/recruitmentTask

**Comment by Salonce** [comment]
Issues fixed
