### ISSUE TITLE
Użyjj queryParam zamiast 2 endpointów

### ISSUE THREAD

**Issue by johnny333** [Salonce/WeatherAndClothes#7]
https://github.com/Salonce/WeatherAndClothes/blob/404f2f20526db4d1a439aee1e5a253b8be1bc9e0/src/main/java/springTwo/example/springProject/Weather/WeatherController.java#L42

zrób endpoint do szukania po wielu zadanych parametrach nie zależnie ile ich jest, nie wydzielaj każdego parametru do osobnej obsługi

**Comment by Salonce** [comment]
issue fixed
