### ISSUE TITLE
Używaj metod opisanych standardem REST API 

### ISSUE THREAD

**Issue by johnny333** [Salonce/WeatherAndClothes#8]
https://github.com/Salonce/WeatherAndClothes/blob/404f2f20526db4d1a439aee1e5a253b8be1bc9e0/src/main/java/springTwo/example/springProject/Item/ItemController.java#L38

Wszystko obsługujesz tu postem, a masz do wyboru jeszcze get, post, patch, delete, put

**Comment by Salonce** [comment]
issue fixed
