### ISSUE TITLE
Może zamiast TokenConfig OpenWeatherMapConfig

### ISSUE THREAD

**Issue by johnny333** [Salonce/WeatherAndClothes#9]
https://github.com/Salonce/WeatherAndClothes/blob/404f2f20526db4d1a439aee1e5a253b8be1bc9e0/src/main/java/springTwo/example/springProject/TokenConfig.java#L8

Nie przyda Ci się to do niczego innego wiec nie ma co uogólniać, po zmianie nazwy to miejsce gdzie powinieneś kleic string z adresem do usługi a w Serwisie juz tylko go używać

**Comment by Salonce** [comment]
Dzięki za wszystkie wskazówki.

**Comment by Salonce** [comment]
issue fixed
